### ISSUE TITLE
Complete PHP support

### ISSUE THREAD

**Issue by cfroystad** [tree-sitter/tree-sitter-php#58]
After seeing discussions about bumping parsers to 1.0 after tree-sitter 1.0 is released, I figured it'd be good to list what remains to be done before having full support for parsing PHP using tree-sitter. I guess most of these should be solved before tree-sitter-php is bumped to 1.0 - at least if a 1.0 release means committing to not changing the AST.

This list is compiled from testing the code of PHP release announcements (from 7.0). Thus, I might have missed something. Feel free to add it if that's the case.

### Pre 7.0
- [x] Interpolated strings (#34, PR: #72)
- [x] Represent references (PR: #106)
- [x] Add support for interpolated string content in heredoc (PR: #121)
- [x] Ensure all keywords are handled as such ([documentation](https://www.php.net/manual/en/reserved.keywords.php))
- [x] Make 'yield' and 'yield from' distinguishable in the AST
- [x] Handle interpolation in Execution Operators (backtick) ([documentation](https://www.php.net/manual/en/language.operators.execution.php), PR: #146)

### 7.1
- [x] Symmetric array destructuring ([rfc](https://wiki.php.net/rfc/short_list_syntax))
- [x] Multi catch exception handling ([rfc](https://wiki.php.net/rfc/multiple-catch))

### 7.4
- [x] Arrow functions ([rfc](https://wiki.php.net/rfc/arrow_functions_v2), PR: #65)
- [x] Null coalescing assignment operator ([rfc](https://wiki.php.net/rfc/null_coalesce_equal_operator))
- [x] Unpacking inside arrays ([rfc](https://wiki.php.net/rfc/spread_operator_for_array), PR: #64)
- [x] Numeric literal separator ([rfc](https://wiki.php.net/rfc/numeric_literal_separator))

### 8.0
- [x] Named arguments ([rfc](https://wiki.php.net/rfc/named_params), PR: #67)
- [x] Attributes ([rfc](https://wiki.php.net/rfc/attributes_v2), PR: #69)
- [x] Add support for attribute groups to support round tripping and other use cases than highlighting (PR: #130)
- [x] Constructor property promotion ([rfc](https://wiki.php.net/rfc/constructor_promotion), PR: #74)
- [x] Union types ([rfc](https://wiki.php.net/rfc/union_types_v2), PR: #68)
- [x] Match expression ([rfc](https://wiki.php.net/rfc/match_expression_v2), PR: #73)
- [x] Nullsafe operator ([rfc](https://wiki.php.net/rfc/nullsafe_operator), PR: #75)
- [x] Allow trailing comma in parameter list ([rfc](https://wiki.php.net/rfc/trailing_comma_in_parameter_list), PR: #66)
- [x] Allow trailing comma in closure use lists ([rfc](https://wiki.php.net/rfc/trailing_comma_in_closure_use_list), PR: #66)
- [x] non-capturing catches - ([rfc](https://wiki.php.net/rfc/non-capturing_catches))
- [x] throw expression ([rfc](https://wiki.php.net/rfc/throw_expression), PR: #76)
- [ ] Deprecate left-assossiative ternary operator ([rfc](https://wiki.php.net/rfc/ternary_associativity))

### 8.1
- [x] Enums ([rfc](https://wiki.php.net/rfc/enumerations), PR: #89)
- [x] Explicit octal integer literal notation ([rfc](https://wiki.php.net/rfc/explicit_octal_notation), PR: #87)
- [x] Final class constants ([rfc](https://wiki.php.net/rfc/final_class_const), PR: #88)
- [x] Pure intersection types ([rfc](https://wiki.php.net/rfc/pure-intersection-types), PR: #145)
- [x] Readonly properties 2.0 ([rfc](https://wiki.php.net/rfc/readonly_properties_v2), PR: #134)
- [x] New in initializers ([rfc](https://wiki.php.net/rfc/new_in_initializers))
- [x] First class callable syntax ([rfc](https://wiki.php.net/rfc/first_class_callable_syntax), PR: #137)
- [x] noreturn return type ([rfc](https://wiki.php.net/rfc/noreturn_type), PR: #138)

In addition, there should be some house cleaning ensuring proper names on AST nodes. E.g. class_modifier is used for both classes and functions.

I'll try to get to these over time, but will not be able to get through all of them in the near future. So if anyone else wants to grab an item, I won't complain 😄

**Comment by maxbrunsfeld** [comment]
Thanks for writing this up.

**Comment by cfroystad** [comment]
The remaining items i'll try to get to after the current PRs been reviewed and potentially merged. Don't stress about it - I understand there are other priorities in life and at work 🙂

**Comment by cfroystad** [comment]
With the last commits, we're at full compatibility all the way to PHP 8.1

I'm sure there's some bugs I've yet to identify. I've been playing with an idea of creating a test system with AST translation between tree-sitter-php and the "official" [php-ast](https://github.com/nikic/php-ast) to ensure we're complete and correct. Though this is still on the "eventually" list...

I hope we'll be fully compatible with PHP 8.2 before its release (though I'll be careful with promises, because life). 

Note: There's still one unchecked box on this list due to the ternary operator being left-assosiative before PHP 8. I've opted to leave this as a TODO in the code until the moment we decide to only support PHP8 and upwards (however, in the case of the concatenation precedence we currently favor PHP8 and leaves to the next layer to translate it back to the PHP7 interpretation if required). Let me know if you'd like me to handle this differently

**Comment by unansweredocd** [comment]
Folks, thank you so much for all the work that you're doing. Making it that much easier to work on php!
